dist: trusty

language: node_js
node_js:
  - '10'

cache:
  directories:
    - 'node_modules'

env:
  - CI_ENV=travis

install:
  - npm install

script:
  - commitlint-travis
  - npm run lint
  - npm test
  - npm run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  # Set in the settings page of your repository, as a secure variable
  github-token: $GITHUB_TOKEN
  repo: hxfdarling/imt
  keep-history: true
  target-branch: master
  on:
    branch: master
