dist: trusty

language: node_js
node_js:
  - '10'

cache: npm

env:
  - CI_ENV=travis

install:
  - npm install

script:
  - commitlint-travis
  - npm run lint
  - npm test
deploy:
  - provider: script
    script: deploy.sh
    on:
      branch: docs